### ISSUE TITLE
license to use? (not an issue)

### ISSUE THREAD

**Issue by hyusetiawan** [brunobord/pomodorock#28]
I am interested in hosting this pomodoro app on [unopico](https://unopi.co), there is no usage license however and I dont want to step on anyone's toes :) Mind adding a license to use?

**Comment by brunobord** [comment]
Hello. There's already a (very permissive) License, visible on the [Readme](https://github.com/brunobord/pomodorock/blob/gh-pages/README.md#license). The WTFPL allows you to do _what the fuck you want_ with this software.

So, that's a green light to use it, host it, modify it, redistribute it, whatever.

Have fun.
