### ISSUE TITLE
Use HTML5 notifications to warn when a pomodoro ends

### ISSUE THREAD

**Issue by nfroidure** [brunobord/pomodorock#8]

**Comment by brunobord** [comment]
mmm... I wish this could work.
Looks like it's not supported by chrome, safari and firefox: http://www.html5rocks.com/en/tutorials/notifications/quick/

even  `window.webkitNotifications.requestPermission();`doesn't trigger anything...

**Comment by nfroidure** [comment]
Using requestPermission will only insside a user interaction event callback (click on a button)

**Comment by brunobord** [comment]
interesting. will investigate later on.

**Comment by brunobord** [comment]
done, see `notifications` branch: https://github.com/brunobord/pomodorock/tree/notifications
has been merged in the main branch.
